export const pointCodes = {
  'admissions': 'ea01',
  'admissions-o': 'ea02',
  'approval': 'ea03',
  'approval-o': 'ea04',
  'arrow-down': 'ea05',
  'arrow-up': 'ea06',
  'ascending': 'ea07',
  'assess': 'ea08',
  'assess-o': 'ea09',
  'bell': 'ea0a',
  'bell-o': 'ea0b',
  'business': 'ea0c',
  'business-o': 'ea0d',
  'calendar': 'ea0e',
  'calendar-o': 'ea0f',
  'capital': 'ea10',
  'capital-o': 'ea11',
  'caret-down': 'ea12',
  'cashier': 'ea13',
  'cashier-desk-o': 'ea14',
  'cashier-o': 'ea15',
  'channel-o': 'ea16',
  'chart': 'ea17',
  'chart-o': 'ea18',
  'check': 'ea19',
  'checkin': 'ea1a',
  'checkin-o': 'ea1b',
  'clock': 'ea1c',
  'clock-o': 'ea1d',
  'close': 'ea1e',
  'closed-eye': 'ea1f',
  'contract-o': 'ea20',
  'countdown': 'ea21',
  'coupon': 'ea22',
  'coupon-o': 'ea23',
  'course': 'ea24',
  'course-o': 'ea25',
  'customer': 'ea26',
  'customer-o': 'ea27',
  'development-doc': 'ea28',
  'development-doc-o': 'ea29',
  'distribution-o': 'ea2a',
  'doc': 'ea2b',
  'double-last': 'ea2c',
  'double-next': 'ea2d',
  'down': 'ea2e',
  'down-circle': 'ea2f',
  'down-circle-o': 'ea30',
  'download': 'ea31',
  'drag': 'ea32',
  'edit': 'ea33',
  'edit-o': 'ea34',
  'educational': 'ea35',
  'educational-o': 'ea36',
  'error-circle': 'ea37',
  'error-circle-o': 'ea38',
  'expand-customer': 'ea39',
  'expand-customer-o': 'ea3a',
  'export': 'ea3b',
  'feedback': 'ea3c',
  'filter-o': 'ea3d',
  'finance': 'ea3e',
  'finance-o': 'ea3f',
  'flow-o': 'ea40',
  'folder-o': 'ea41',
  'fullscreen-exit': 'ea42',
  'gift': 'ea43',
  'gift-o': 'ea44',
  'goods': 'ea45',
  'goods-o': 'ea46',
  'hc-manage': 'ea47',
  'hc-manage-o': 'ea48',
  'help': 'ea49',
  'help-o': 'ea4a',
  'hotel': 'ea4b',
  'hotel-o': 'ea4c',
  'hotline-o': 'ea4d',
  'hr': 'ea4e',
  'hr-o': 'ea4f',
  'im-o': 'ea50',
  'info-circle': 'ea51',
  'info-circle-o': 'ea52',
  'inventory': 'ea53',
  'inventory-o': 'ea54',
  'jump-out': 'ea55',
  'knowledge': 'ea56',
  'knowledge-o': 'ea57',
  'left': 'ea58',
  'left-circle': 'ea59',
  'left-circle-o': 'ea5a',
  'link': 'ea5b',
  'loading': 'ea5c',
  'lock': 'ea5d',
  'lock-o': 'ea5e',
  'marketing': 'ea5f',
  'marketing-o': 'ea60',
  'member-o': 'ea61',
  'message': 'ea62',
  'message-o': 'ea63',
  'mini-apps': 'ea64',
  'mini-apps-o': 'ea65',
  'more': 'ea66',
  'nav-grid': 'ea67',
  'nav-line': 'ea68',
  'open-folder-o': 'ea69',
  'order': 'ea6a',
  'order-o': 'ea6b',
  'pending-payment-o': 'ea6c',
  'photo': 'ea6d',
  'photo-o': 'ea6e',
  'pin': 'ea6f',
  'pin-o': 'ea70',
  'plus': 'ea71',
  'plus-circle': 'ea72',
  'plus-circle-o': 'ea73',
  'procurement': 'ea74',
  'procurement-o': 'ea75',
  'qa-o': 'ea76',
  'qrcode': 'ea77',
  'refresh': 'ea78',
  'remove': 'ea79',
  'remove-o': 'ea7a',
  'report': 'ea7b',
  'report-forms': 'ea7c',
  'report-forms-o': 'ea7d',
  'report-o': 'ea7e',
  'reset': 'ea7f',
  'right': 'ea80',
  'right-circle': 'ea81',
  'right-circle-o': 'ea82',
  'rights-list-o': 'ea83',
  'salesman-o': 'ea84',
  'save': 'ea85',
  'save-o': 'ea86',
  'scan-code-o': 'ea87',
  'search': 'ea88',
  'service': 'ea89',
  'service-o': 'ea8a',
  'settings': 'ea8b',
  'settings-o': 'ea8c',
  'share': 'ea8d',
  'shop': 'ea8e',
  'shop-analyze-o': 'ea8f',
  'shop-decorate': 'ea90',
  'shop-decorate-o': 'ea91',
  'shop-o': 'ea92',
  'show': 'ea93',
  'show-o': 'ea94',
  'sign-out': 'ea95',
  'smile': 'ea96',
  'star': 'ea97',
  'star-o': 'ea98',
  'strategy-o': 'ea99',
  'subtract-circle': 'ea9a',
  'subtract-circle-o': 'ea9b',
  'success-circle': 'ea9c',
  'success-circle-o': 'ea9d',
  'suggestions': 'ea9e',
  'summary': 'ea9f',
  'summary-o': 'eaa0',
  'table-compact': 'eaa1',
  'table-loose': 'eaa2',
  'tendency-o': 'eaa3',
  'text-guide-o': 'eaa4',
  'thumbnail': 'eaa5',
  'ticket': 'eaa6',
  'ticket-o': 'eaa7',
  'tools-o': 'eaa8',
  'unlock': 'eaa9',
  'unlock-o': 'eaaa',
  'up': 'eaab',
  'up-circle': 'eaac',
  'up-circle-o': 'eaad',
  'upload': 'eaae',
  'video': 'eaaf',
  'video-o': 'eab0',
  'visit-o': 'eab1',
  'voice': 'eab2',
  'wait': 'eab3',
  'warning': 'eab4',
  'warning-o': 'eab5',
  'wechat': 'eab6',
  'wechat-o': 'eab7',
  'withdraw-cash-o': 'eab8',
  'youzan': 'eab9',
  'youzan-o': 'eaba'
}

export default [
  'admissions',
  'admissions-o',
  'approval',
  'approval-o',
  'arrow-down',
  'arrow-up',
  'ascending',
  'assess',
  'assess-o',
  'bell',
  'bell-o',
  'business',
  'business-o',
  'calendar',
  'calendar-o',
  'capital',
  'capital-o',
  'caret-down',
  'cashier',
  'cashier-desk-o',
  'cashier-o',
  'channel-o',
  'chart',
  'chart-o',
  'check',
  'checkin',
  'checkin-o',
  'clock',
  'clock-o',
  'close',
  'closed-eye',
  'contract-o',
  'countdown',
  'coupon',
  'coupon-o',
  'course',
  'course-o',
  'customer',
  'customer-o',
  'development-doc',
  'development-doc-o',
  'distribution-o',
  'doc',
  'double-last',
  'double-next',
  'down',
  'down-circle',
  'down-circle-o',
  'download',
  'drag',
  'edit',
  'edit-o',
  'educational',
  'educational-o',
  'error-circle',
  'error-circle-o',
  'expand-customer',
  'expand-customer-o',
  'export',
  'feedback',
  'filter-o',
  'finance',
  'finance-o',
  'flow-o',
  'folder-o',
  'fullscreen-exit',
  'gift',
  'gift-o',
  'goods',
  'goods-o',
  'hc-manage',
  'hc-manage-o',
  'help',
  'help-o',
  'hotel',
  'hotel-o',
  'hotline-o',
  'hr',
  'hr-o',
  'im-o',
  'info-circle',
  'info-circle-o',
  'inventory',
  'inventory-o',
  'jump-out',
  'knowledge',
  'knowledge-o',
  'left',
  'left-circle',
  'left-circle-o',
  'link',
  'loading',
  'lock',
  'lock-o',
  'marketing',
  'marketing-o',
  'member-o',
  'message',
  'message-o',
  'mini-apps',
  'mini-apps-o',
  'more',
  'nav-grid',
  'nav-line',
  'open-folder-o',
  'order',
  'order-o',
  'pending-payment-o',
  'photo',
  'photo-o',
  'pin',
  'pin-o',
  'plus',
  'plus-circle',
  'plus-circle-o',
  'procurement',
  'procurement-o',
  'qa-o',
  'qrcode',
  'refresh',
  'remove',
  'remove-o',
  'report',
  'report-forms',
  'report-forms-o',
  'report-o',
  'reset',
  'right',
  'right-circle',
  'right-circle-o',
  'rights-list-o',
  'salesman-o',
  'save',
  'save-o',
  'scan-code-o',
  'search',
  'service',
  'service-o',
  'settings',
  'settings-o',
  'share',
  'shop',
  'shop-analyze-o',
  'shop-decorate',
  'shop-decorate-o',
  'shop-o',
  'show',
  'show-o',
  'sign-out',
  'smile',
  'star',
  'star-o',
  'strategy-o',
  'subtract-circle',
  'subtract-circle-o',
  'success-circle',
  'success-circle-o',
  'suggestions',
  'summary',
  'summary-o',
  'table-compact',
  'table-loose',
  'tendency-o',
  'text-guide-o',
  'thumbnail',
  'ticket',
  'ticket-o',
  'tools-o',
  'unlock',
  'unlock-o',
  'up',
  'up-circle',
  'up-circle-o',
  'upload',
  'video',
  'video-o',
  'visit-o',
  'voice',
  'wait',
  'warning',
  'warning-o',
  'wechat',
  'wechat-o',
  'withdraw-cash-o',
  'youzan',
  'youzan-o'
]
